# Generated by Django 2.0.7 on 2018-07-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamp',
            name='location',
            field=models.CharField(default='Krk', max_length=200),
        ),
        migrations.AlterField(
            model_name='radionica',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
