# Generated by Django 2.0.7 on 2018-07-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0002_auto_20180706_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kamp',
            name='end_date',
            field=models.DateField(verbose_name='Kraj kampa'),
        ),
        migrations.AlterField(
            model_name='kamp',
            name='start_date',
            field=models.DateField(verbose_name='Pocetak kampa'),
        ),
    ]
