# Generated by Django 2.0.7 on 2018-07-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0003_auto_20180706_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='radionica',
            name='difficulty',
            field=models.CharField(choices=[('b', 'Pocetna'), ('e', 'Lagana'), ('i', 'Srednja'), ('a', 'Napredna'), ('x', 'Experti'), ('o', 'Olimpijci')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='radionica',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Kraj radonice'),
        ),
        migrations.AddField(
            model_name='radionica',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Pocetak radonice'),
        ),
    ]
